name: Release

on:
  push:
    tags:
      - 'v*'           # e.g. v1.0.0, v2.1.3
    branches:
      - main

permissions:
  contents: write     # allows creating releases + uploading assets

jobs:
  # ────────────────────────────────────────────────────────────────────────
  # 1. CREATE RELEASE (runs only once)
  # ────────────────────────────────────────────────────────────────────────
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:    ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft:       false
          prerelease:  false

  # ────────────────────────────────────────────────────────────────────────
  # 2. BUILD & UPLOAD ASSETS (matrix)
  # ────────────────────────────────────────────────────────────────────────
  build_and_upload:
    name: Build & Upload Assets
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifact directory
        run: mkdir -p dist

      - name: Copy & rename binary
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp "target\\${{ matrix.target }}\\release\\mytool${{ matrix.ext }}" "dist/mytool-${{ matrix.target }}${{ matrix.ext }}"
          else
            cp target/${{ matrix.target }}/release/mytool${{ matrix.ext }} dist/mytool-${{ matrix.target }}${{ matrix.ext }}
          fi

      - name: Generate SHA256 checksum
        working-directory: dist
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            powershell -Command "Get-FileHash -Algorithm SHA256 mytool-${{ matrix.target }}${{ matrix.ext }} | ForEach-Object { \"$($_.Hash) *mytool-${{ matrix.target }}${{ matrix.ext }}\" } | Out-File -Encoding utf8 mytool-${{ matrix.target }}${{ matrix.ext }}.sha256"
          else
            sha256sum mytool-${{ matrix.target }}${{ matrix.ext }} > mytool-${{ matrix.target }}${{ matrix.ext }}.sha256
          fi

      - name: Upload binary asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url:     ${{ needs.create.outputs.upload_url }}
          asset_path:     dist/mytool-${{ matrix.target }}${{ matrix.ext }}
          asset_name:     mytool-${{ matrix.target }}${{ matrix.ext }}
          asset_content_type: application/octet-stream

      - name: Upload checksum asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url:     ${{ needs.create.outputs.upload_url }}
          asset_path:     dist/mytool-${{ matrix.target }}${{ matrix.ext }}.sha256
          asset_name:     mytool-${{ matrix.target }}${{ matrix.ext }}.sha256
          asset_content_type: text/plain
