name: Release

on:
  push:
    tags: ['v*']
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Build & Publish Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux build
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          # Windows build
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
          # macOS build
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""

    steps:

      # ┌────────────────────────────────────────────────────────────────────┐
      # │ 1. PREPARE SOURCE                                                   │
      # └────────────────────────────────────────────────────────────────────┘
      - name: Checkout repository
        uses: actions/checkout@v4

      # ┌────────────────────────────────────────────────────────────────────┐
      # │ 2. SET UP TOOLCHAIN                                                │
      # └────────────────────────────────────────────────────────────────────┘
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      # ┌────────────────────────────────────────────────────────────────────┐
      # │ 3. BUILD BINARY                                                    │
      # └────────────────────────────────────────────────────────────────────┘
      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      # ┌────────────────────────────────────────────────────────────────────┐
      # │ 4. PREPARE DISTRIBUTABLE                                           │
      # └────────────────────────────────────────────────────────────────────┘
      - name: Create distribution folder
        run: mkdir -p dist

      - name: Copy and rename binary (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cp \
            target/${{ matrix.target }}/release/favis${{ matrix.ext }} \
            dist/favis-${{ matrix.target }}${{ matrix.ext }}

      - name: Copy and rename binary (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Copy-Item -Path "target\${{ matrix.target }}\release\favis${{ matrix.ext }}" -Destination "dist\favis-${{ matrix.target }}${{ matrix.ext }}"

      # ┌────────────────────────────────────────────────────────────────────┐
      # │ 5. GENERATE CHECKSUM                                               │
      # └────────────────────────────────────────────────────────────────────┘
      - name: Generate SHA256 checksum (Linux)
        if: runner.os == 'Linux'
        working-directory: dist
        run: sha256sum favis-${{ matrix.target }}${{ matrix.ext }} > favis-${{ matrix.target }}${{ matrix.ext }}.sha256

      - name: Generate SHA256 checksum (macOS)
        if: runner.os == 'macOS'
        working-directory: dist
        run: shasum -a 256 favis-${{ matrix.target }}${{ matrix.ext }} > favis-${{ matrix.target }}${{ matrix.ext }}.sha256

      - name: Generate SHA256 checksum (Windows)
        if: runner.os == 'Windows'
        working-directory: dist
        shell: powershell
        run: |
          $hash = (Get-FileHash -Algorithm SHA256 favis-${{ matrix.target }}${{ matrix.ext }}).Hash.ToLower()
          $hash + " *favis-${{ matrix.target }}${{ matrix.ext }}" | Out-File -Encoding utf8 favis-${{ matrix.target }}${{ matrix.ext }}.sha256

      # ┌────────────────────────────────────────────────────────────────────┐
      # │ 6. CREATE & UPLOAD RELEASE                                         │
      # └────────────────────────────────────────────────────────────────────┘
      - name: Publish GitHub Release & Upload Assets
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/favis-${{ matrix.target }}${{ matrix.ext }}
            dist/favis-${{ matrix.target }}${{ matrix.ext }}.sha256
          generate_release_notes: true
          fail_on_unmatched_files: true
